Tempo: 329.298186s
Objective Value(dc - df) = -8
Palavra(x) = SNNKYNGTLEEYGEEYEECYFLLYCCCLLYHQQQQLQQQQVQVVVLQVDLLVVALASRDSVVSSDDVAVQADSSVVVVQVQQDAAAAAWAWSWWVCWCWSVVVCVGGWCHSPTSCWHHPHLHIHHTTHHHHVYHHHYSHVKSCCEHAAEQKLHWQHHMWWMMQCMQMQMMMWMMMMWMRKRKFFMMMDDKMQKQQDFQDD
dc = 190
df = 198
