Tempo: 301.529243s
Objective Value(dc - df) = -3.000000
Palavra(x) = GGGGGGGGGGGGGGGGGGGGGGGTGATTGGGAAAAAAAAAAAAAGTAGGGGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATTAGGGGAAGATGAGGAAAAAAAAGGAGGAAAAAAAAAAAAAAAAAAAAAAAAAAAATTTTATTTTTTTTTTTTTTTTTTTTTTTTTTTTTTGGGT
dc = 7
df = 5
