Tempo: 408.013366s
Objective Value(dc - df) = -9
Palavra(x) = GKKKNHAKAKKKAENYYYYYYYMEEIIMSDIYYYYYYYYYPSSEYEYYYYEETYEEYLTEERTYYSSLETTLCCEETTTEEEEQTTDSCTPMSRPMRRVSRGMVCCSVMVVCVMSMVGGPQPVSWVPWWWGWWGGRMPVFRFAAPPRVSRPVVSRPSVSSSFFSVFAAVRSSSRRFFSFSFSSSVVVVSRWFVFFWGWNL
dc = 187
df = 196
