Tempo: 314.468384s
Objective Value(dc - df) = -7
Palavra(x) = VQQFQFQVVQLVFVFFVQSSLFYLLSQQQLYQLYQYYQYMLSLLSSNMYSRLLLLLRYCRMLYLMLKKLKKKLKKLLLLLKLDDLLQQKKQECQQMMQCRPPDPWPDQDDDDDPTTPTTTTDTTTTDTTTTTTTTTTTTTTHHDDERETTEEEEEEDTTNTTIDTTTITTSEVVVTTTTTTTEEVDDEIIEIEEEEVSSS
dc = 192
df = 199
