Tempo: 302.378409s
Objective Value(dc - df) = -3
Palavra(x) = IFIFFFFFWFFFIFFIIFFFFFFFFFFIFIIIFIIFIIIFFFAFFFFFFFFFFFFFFFFFFFFWWFFFHNFHSAAHHHQNNEWWEEEGEESGEERWWEKEWWQQQQQQQQHQQQQQQQQRQQQREQEWEELRLLLLLWLLRWRWLLEELLERLLRERERELLLLELLLLLELLLLLMLLLHHHMMHSMHMHHYYYFYPPP
dc = 191
df = 194
