Tempo: 306.914980s
Objective Value(dc - df) = -3
Palavra(x) = GGGGAACGGGGGTTTTGGTGGGGGGGGGGGGGGGGGGTGTTTTTGTTGTGGTTTGGGTTGGTTTGGGTGGGGGGGGGGGGCCCCCCGCCTTTTTGGGGGGGGGGGGATTTGTGGCTTTTATTTTTAATAAAAAAAAAAAATTTTTTTATTTTAATATTTTATATTATTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
dc = 144
df = 147
