Tempo: 368.616688s
Objective Value(dc - df) = -9
Palavra(x) = AIACRIPRRILIIRMPIITPWWKWYCSYYSWWYCCCCWCTTWCCCTTWWCCCCWCYMYYCYNPNYYMMPYMDYYMYYMYLPPLYYLYYSYDDYSDDYYDYLDPYVYYYYYDYIIYIIHYDWWWSWIVSIRPSCSNHSWNCSNHSPHNSSSSSSSNSCNCNRNRPRRRTRRDRRCHHRRCPHKPVPHPDMDCCCCMCCWHM
dc = 188
df = 197
