Tempo: 301.692653s
Objective Value(dc - df) = -10
Palavra(x) = TTTTTTTTTTGTTTTGAACAAAAAAAAGGGGGAAAGGAGGGGGGGGGGGGGGGGGGGGGGCGCCCCGCCGCCCCCCCCCCCCCGCCCCCCCCCTCCCCCTTCTTTTTTTTTTTTTTTGTTTTTTTTTTTTGTTGGTGGGGGGGTTTTTTTTTTTTTTTTTTTATTTTTTTTTTTTTTTTGGGGGGGGGGGGCTGTTGTTT
dc = 139
df = 149
