Tempo: 303.208630s
Objective Value(dc - df) = -22
Palavra(x) = TTGGGGGGGGGAAGGAGGGAAAAGAAAAAAAAAAAAAAAAAAGTAGAATATTTAATTAAATCTAAAAAAGTTGGGAGACGACGGGGGCCGGCTGCGCGGCTTTTTTTTTTTTGGGTCTCCTCCGTTCTCCCCTCTTCCTTATTTTTCCTTTCTGTGTCTACTAAACCAACAAACCAAAAAAAAAAAAAGAAAAAAAAATA
dc = 143
df = 165
