Tempo: 308.343088s
Objective Value(dc - df) = -3
Palavra(x) = IICCCCFFFFFFFCCECEEEFFEERRIKFFAFAEAAAGGAGAGGGGGGKSKKKWWKKKKKRRWRWWWWVVWWHVVVVVVHSVSHDPPPPPPPPDPPDPDDPPPPPPPPPPDPPPPPPQQPPPPPPPPLLLLLLLLYWWWWWWWEEMMGGMGGMWWWWWWHWWHHHMIWIMMIHWHHIHHHHHHHMMHMIMMMMMMRMMMM
dc = 188
df = 191
