Tempo: 301.529243s
Objective Value(dc - df) = 5.000000
Palavra(x) = GGGGGGGGGGGGGGGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATTTTTTAAAAAAAAAATAAGAAAAAGGGGGCGGCGGGGCCGGGGCCCTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTCTTTTTTCCCCCCCCCTTTCTTGTGTTTTCAACCCCCACCAAAAAAAAAAAAAAAAAAAAAAAAAAAA
dc = 7
df = 5
