Tempo: 306.771021s
Objective Value(dc - df) = -23
Palavra(x) = CGCGCACGAGAAGTTTGGGGTGGGGGGTTGGGTTGTTTGTGTGTGGTGATTTTGTTGTGGGTGGGTTGGAAAGGGACGGGGGGGGCCTATACGTTGGGTGGTTCAATTAAGAACTTCATTATATATAAAATTTTAAATTAAATTTAAATTTTTAAATTTATGTTAATAATTTTTTTTTTTTTTTTTTTTTTTGTTTTTTT
dc = 141
df = 164
