Tempo: 313.969179s
Objective Value(dc - df) = -25
Palavra(x) = CTGATAATTAAGTAGCAGAGCGCACCATGAGCGCGTCGGCGGGGTGTCGCGGTGCGCGTGTGCGCTGGGCGGTCTTTTACTCGGTTTTGTGGCTTCCATACCCATCATAACATATGTGGAAATTTGTGTTGTGGGTGGTTTAAGATGGGTCTTTGGAATGTCCAATTTCCTACCTTCTTCAAATACAAGCCGTGTTGGTT
dc = 138
df = 163
