Tempo: 301.529243s
Objective Value(dc - df) = 4.000000
Palavra(x) = TTAAAAATAAAAAAAAGAAGGGCAAGAAAGGGGGGGGGGCCCCCGCGGTTGGGGGGGGGTCCCGCCCGTGCCCCCCTAATTGTATTTTTTTTTTAAAAAAATAAAATAATTTTTATTTTTGGGTGGGGTTTTTTTTTTTTTTTATGGTTTTTTTTTTTTTTAACCACCTTTCCCCCCCCCCATCACACCGCGGTTTGTCC
dc = 7
df = 5
