Tempo: 302.755854s
Objective Value(dc - df) = -7
Palavra(x) = CNNNNNNNNNNCCHHNNNNNHHHVVVKNNKKKKKKNNNNNNNNNNNNNNNVVVVVVVVVVVVVVNNVVVVVVVVVVVVVVVVIHIIIGIIIIIIWWNWWWWWWTVGGGTTTTTTTTITTTTTTTTTYTTQQQCCQQLQCLQLLLLLLLLLLLLLLLLLSYLSGYNNNNNSSSSSYYYYYYYYYSYYYYYWWWWYWYYYYY
dc = 186
df = 193
