Tempo: 313.883959s
Objective Value(dc - df) = -1
Palavra(x) = TAAAAAATTTTAAAAAGGAGGGCAAGAAAGGGGGGGGCGCCCGCGCGGTTGGGGGGGGGTCCCGCCCGTGCCCCCTCAATTGTAGTTTTTTTTTAAAAAAACAAAATTAATTTTATTTTTGGTTTTGGTTTTTTTTTTTTTTTATTGTTTTTTTTTTTTTTAACCACCTTTCCCCCCCCCACTCACACCGCGTTTTGCCC
dc = 141
df = 142
