Tempo: 301.529243s
Objective Value(dc - df) = 2.000000
Palavra(x) = RRIIIIRRIWRRLWIIIIIIIWLLCAWYYCCCWWCWCWWWWWWWWCCTWWYWCWWWYYYYYYYYYYMYYYMMPPPYYYYYYYYYYYLYSLYDDYYYYYYYYYYYYYYYYDDIDDIIIYYSSDWDWVVVYRCDSWSSNNNWDNPNNHNSNNNSNSSNNNRRNPPRRRRRRRRHCCCCCCCHHHPPPPCPPMCWWWMMMMWW
dc = 7
df = 5
