Tempo: 311.887372s
Objective Value(dc - df) = -19
Palavra(x) = GGGGGGGGGTTCTCATCCGCGGGGGGGGGGGGGGTTGTGTTCCCTTTTTCCCTTTTTTTTTGGTGCCAAAATAATATTTAAAAATAATTAAAATTATATTATCTAGCCACCAATTAAATTATAAGGTGAAGGAAGAGAGTACAGCGGTAGGGGGTGTTGTTTGTGGGTGTGGGGTTTTGGGCCCGCCCGCCGCGCCTCAT
dc = 147
df = 166
