Tempo: 318.198154s
Objective Value(dc - df) = -8
Palavra(x) = YSVVSVSSVQQVVVVQVQQVVTLTVTVNFHNVVNFFFANNINMNNNNHMNNNNAMEELIITETKTTKLKKKNTEIGEEECVEEKKCEKCEECEPPPLLLELLELLEEEEELELSELLLEESSLLELVCLCCVLVDVVLLLLVVLVVVVVVVHMHDDLDVDDLHMLMADDDDDDMMDDDMMNDDMNNDMGMGMMGQGGMEG
dc = 190
df = 198
