Tempo: 301.529243s
Objective Value(dc - df) = 10.000000
Palavra(x) = AATAAAAAAAAAAAAAAAAAAATTTTAAACCACAATCAAAAAAAAAAAAAACCTTCTCCCCCTTTGTGTTTTTTTTTTTTTTTTTTTTTTTGGAAAAGGAGAGAAAAGAAAAGAAAAAAAAAAAAAAAAACGGGGGGAGGAACCCAGGGGGGGACCGATCCCTAAAACAAATAAAAGGGGAAAAGGAAAACCCACAAAAC
dc = 7
df = 5
