Tempo: 302.301983s
Objective Value(dc - df) = -9
Palavra(x) = FIEFIFFIFFIIFIFIIIIFIFFFFFFFIFIFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFPFWFFWWWNFHSAHHQTRNQWQQEEEGEEWEEEEEWEEWWWQQQQQQQEQQQQQQQQQRLQQREWELLLLRLLLLLLLLRRLWLEELLLLLLLRERRREELLLLLLELHELLLLLMLLLHHHMMMHHHMMHYYHHMYPP
dc = 190
df = 199
