Tempo: 301.529243s
Objective Value(dc - df) = 14.000000
Palavra(x) = GCGAGGGGGGGTTTTTTTTTGGTTTTTTTTTTCTTCCCTCCCCCGTGGGGGGGGGGTGGGGATGTTTTTTTTTTTTTTGGGTTTTTGTTTTTATTCCAACAACAAAAAAAAATTATTCCTTTTTTTCTTTCGCCCGATGTTTGTGTTACTTTTTGGTATTCTAAAAAAAAAAAAGCATTTTAACCTTTAATTTTTTTTTA
dc = 7
df = 5
