Tempo: 316.295384s
Objective Value(dc - df) = -11
Palavra(x) = CWCWGCWGWWCWWCWWCGYWHHCCHWCCWTCTYTWWWYYTCTYCYYWIICWIIIWWIWIIWWPWIFKWWQQFQIQIIKIICGCDCGFDGFGRFDEKRRERGRQRQQRQRRRQERRRRREERDEDRRRRREEEFRFFFRRFFFDRFEMRYMSFCDTMYEESRSTSSHHSCSSTTSQDDLPVSNVVAHAECDIGLGLGAGGH
dc = 186
df = 197
