Tempo: 302.643564s
Objective Value(dc - df) = -12
Palavra(x) = CMNNNNMFNNNCNHVHHHHHHHHVVHVNVNNNKKKNNNNNNNVNNNNNNNVNVVVVVVVVVVNVVNVVVVVVVVVVVVVHIHIHIVIGWIWWIIIINWWWWHNHNGWGTTTQTQTTITTTTTTTTYYYQQQQCLQCCCCLQCQLFLNLLLLLLLLLLLLKLSKKYNYNNNSYYSSYYYYLYYSSYSYSNSYWYYWWWWYN
dc = 186
df = 198
