Tempo: 307.390421s
Objective Value(dc - df) = -21
Palavra(x) = TTATTTATTTATAATATAAATATTTTTGGTTCACATTACCATAATACAACTTTCTTCCCTTTGTTTTGGGTTTTTTCGTTTGGTTTTTGGAACGGGAAACAAGGAGGAGAGAAAACAGGGACCGAAAGAGAGGGAGGGCCGACAGGGCCAAGACACTCAACCTTAGCGGTGATAAAGTGAAGGAGGGAAGCAAGTCTAAA
dc = 141
df = 162
