Tempo: 317.576862s
Objective Value(dc - df) = -22
Palavra(x) = TTTTAATTTTTTTTTTTTTCTTTTTTTTTGTTCCGGGGTGGGTCTTAGCAGTTGCCGCTGTGCGCGCGCCGTTCCGCCCTCGCCCTGTTCCTGGTTCAGAGTAAAAGAGCTTGGTCCGCCGCTTGGGGGGGCGCCTCGGGAGCAGCGTTGGCGTCCGCGCGGCAGGTTAGTTAGTAAGAATAGGATTGATTTATATATTT
dc = 140
df = 162
