Tempo: 304.525078s
Objective Value(dc - df) = -1
Palavra(x) = FQAAQTMQWMWFWFFMWWYWWFWWMWMMFTYYYYYYMMYMVHMMPTYTAEMMMAMVVMMAMMAMMYMYMYYMQMMQQQRRQRQRRRRRRRRRRRRRRRRRRRRRRRRRRRWWRWRRRWWARWWWWARWWAWWGGARAWKAAWWGAGAAAGAAGARRDDFDFFEFGEDDEEEEEFDDEEEEEEEELEFELDDLLLLWLWLW
dc = 189
df = 190
