Tempo: 304.486891s
Objective Value(dc - df) = -9
Palavra(x) = WWWAWTMTWAAFAMFWWWWFFFWWMWMYFTMCYYYMMYMMYHMMMPVTAMMAVVMMVMMAMVMMMYMMMMMMMMQMMMRRQFRQRRRRRRRRRRRIRRRRRRRRRYRRRRRWRRYRWRYWWAAWAWRWGWAAWWARWAKKKWAGMGGAAAGGDAAGFDFDDEFFDDDDDGEFEFEEEELLLKELEELEDDDLDDLWWWLW
dc = 189
df = 198
