Tempo: 301.648034s
Objective Value(dc - df) = -8
Palavra(x) = GGGGGGGGGGGGGGGGGAAAATGTGAGTAGAAAAAAAAAAAATAGAAAAACGGCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATATATGAGGAGGGGTTGAAAGAAAAAAAAGAGGAGAAAAAAAGAGGAAAAAAAAAAACCATAGTGAGTTTTTTTACTTTATTTATTGTTTTTTTTGTTTT
dc = 142
df = 150
