Tempo: 308.239817s
Objective Value(dc - df) = -11
Palavra(x) = IECCICECCFCCCFCFCCEWEFAEKRIEEEWFASAGGGAASAGKGGKKKSKKWKWKKKKRKWWWGAWKKWHVVVWWSSHSHDHDDDDCDPDDDPPPPPDPDPCVPPVPVVPPPPDPQQPQQPPPLPPLPLLPPLYLYWWWLEMWEWMEGWGGMWWWWWWWWWWIHMWWMIHWHHHMICIIHHIMMHHIIMMMMMMMMMTI
dc = 187
df = 198
