Tempo: 316.757382s
Objective Value(dc - df) = -1
Palavra(x) = CWCWYCWWWWGWCWHHGYCHGWTTCWWTTWWWTTYWWTYCCYTYCYYWCWIWWIWIIIIIWIWIPFIKWQQFQKQQQWCGIFQQDDGGGFGFRFERFDRQQQQRQRRRQRRRERRRREEREDDRDEFRRFREFFRRRFFFRFFRFFMRYMYTSDMDIMEMRSSTDSHTSAMTTAQTYSPGVHSVSEAELLIILLLLAAGL
dc = 187
df = 188
