Tempo: 301.529243s
Objective Value(dc - df) = 12.000000
Palavra(x) = TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTGTTTTCACATGGCGGGCGCCCCCCCCCCTCCCCCCCCCCCCCCCTCTGGTTTTTTTGGTTTATTTTTTTTTCCCCTCCCCCCCCCCCCCCCCCGGGGGGGGAAAGCGCCCCCCCCCCCTATTTTTTAATTTAAAAGAAAAAATAAAAAAAATTAT
dc = 7
df = 5
